// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace IvnMgmt_ASPNET {
	
	
	public partial class _Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label inventoryApp;
		
		protected System.Web.UI.WebControls.Label label4;
		
		protected System.Web.UI.WebControls.Label Label1;
		
		protected System.Web.UI.WebControls.Label Label2;
		
		protected System.Web.UI.WebControls.Label Label3;
		
		protected System.Web.UI.WebControls.Label lblTotalArea;
		
		protected System.Web.UI.WebControls.Label lblWarningLimit;
		
		protected System.Web.UI.WebControls.Label lblErrorLimit;
		
		protected System.Web.UI.WebControls.Label lblTotalUsedArea;
		
		protected System.Web.UI.WebControls.Label Label5;
		
		protected System.Web.UI.WebControls.TextBox txtWarningLimit;
		
		protected System.Web.UI.WebControls.Label Label6;
		
		protected System.Web.UI.WebControls.TextBox txtErrorLimit;
		
		protected System.Web.UI.WebControls.Button btnUpdateSpaceDetails;
		
		protected System.Web.UI.WebControls.Label Label7;
		
		protected System.Web.UI.WebControls.TextBox txtItemName;
		
		protected System.Web.UI.WebControls.Label Label8;
		
		protected System.Web.UI.WebControls.TextBox txtNoOfItems;
		
		protected System.Web.UI.WebControls.Label Label9;
		
		protected System.Web.UI.WebControls.DropDownList trxTypeList;
		
		protected System.Web.UI.WebControls.Label Label10;
		
		protected System.Web.UI.WebControls.TextBox txtAreaPerUnit;
		
		protected System.Web.UI.WebControls.Label Label11;
		
		protected System.Web.UI.WebControls.TextBox txtUnitPrice;
		
		protected System.Web.UI.WebControls.Button btnInsert;
		
		protected System.Web.UI.WebControls.DataGrid dg_InventoryManagement;
		
		protected System.Web.UI.WebControls.Label Label12;
	}
}
